# constants.py

DEFAULT_BRAZE_REST_ENDPOINT = "https://rest.iad-01.braze.com"
TRANSIFEX_API_BASE_URL = "https://rest.api.transifex.com"
DEFAULT_BACKUP_PATH_NAME = "Downloads"
DEFAULT_LOG_LEVEL = "Normal"
DEFAULT_BACKUP_ENABLED = True
DEFAULT_AUTO_UPDATE_ENABLED = True

# Translatable fields
EMAIL_TRANSLATABLE_FIELDS = ["subject", "preheader", "body"]
BLOCK_TRANSLATABLE_FIELDS = ["content"]

# API endpoints
BRAZE_EMAIL_TEMPLATES_LIST_ENDPOINT = "/templates/email/list"
BRAZE_EMAIL_TEMPLATE_INFO_ENDPOINT = "/templates/email/info"
BRAZE_CONTENT_BLOCKS_LIST_ENDPOINT = "/content_blocks/list"
BRAZE_CONTENT_BLOCK_INFO_ENDPOINT = "/content_blocks/info"
TRANSIFEX_RESOURCES_ENDPOINT = "/resources"
TRANSIFEX_RESOURCE_STRINGS_ASYNC_UPLOADS_ENDPOINT = "/resource_strings_async_uploads"
TRANSIFEX_TMX_ASYNC_DOWNLOADS_ENDPOINT = "/tmx_async_downloads"

# Settings keys
KEY_BRAZE_API = "BRAZE_API_KEY"
KEY_TX_API = "TRANSIFEX_API_TOKEN"
KEY_BRAZE_ENDPOINT = "BRAZE_REST_ENDPOINT"
KEY_TX_ORG = "TRANSIFEX_ORGANIZATION_SLUG"
KEY_TX_PROJECT = "TRANSIFEX_PROJECT_SLUG"
KEY_BACKUP_PATH = "BACKUP_PATH"
KEY_LOG_LEVEL = "LOG_LEVEL"
KEY_BACKUP_ENABLED = "BACKUP_ENABLED"
KEY_AUTO_UPDATE = "AUTO_UPDATE_ENABLED"

MANAGED_SETTINGS_KEYS = [
    KEY_BRAZE_API,
    KEY_TX_API,
    KEY_BRAZE_ENDPOINT,
    KEY_TX_ORG,
    KEY_TX_PROJECT,
    KEY_BACKUP_PATH,
    KEY_LOG_LEVEL,
    KEY_BACKUP_ENABLED,
    KEY_AUTO_UPDATE,
]

DEV_AUTO_UPDATE_ENABLED = True

# Platform suffixes for updates
PLATFORM_SUFFIXES = {
    "windows": "win",
    "darwin": "mac",
    "linux": "linux",
}
