# .github/workflows/ci.yml

name: Run Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Checkout code (current branch)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Checkout develop branch into a separate, temporary directory
    # This will contain all files from the develop branch
    - name: Checkout develop branch fully for comparison
      uses: actions/checkout@v4
      with:
        ref: develop
        path: develop-branch-full # Renamed path for clarity
        fetch-depth: 0

    # Manually copy only constants.py from the full develop branch checkout
    # to the main workspace root for the validation script
    - name: Copy specific files from develop branch checkout
      run: cp constants.py ${{ github.workspace }}/develop_constants.py
      working-directory: develop-branch-full # Execute this command inside the full checkout

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Tkinter
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements-dev.txt
        
    # Run Version Validation Script, now knowing develop_constants.py is in the root
    - name: Run Version Validation
      run: python scripts/validate_version.py develop_constants.py # Pass the new path
      working-directory: ${{ github.workspace }} # Ensure script runs from repo root

    - name: Run Tests with Pytest
      run: |
        pytest --cov=. --cov-report=xml