# .github/workflows/ci.yml
# This workflow runs tests on every push and pull request to the main and develop branches.

name: Run Tests

on:
  push:
    # --- FIX: Correctly define the list of branches ---
    branches: [ "main", "develop" ]
  pull_request:
    # --- FIX: This now correctly triggers for PRs TO main or develop ---
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: self-hosted # This job runs on a self-hosted runner
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements-dev.txt
        
    - name: Run Tests with Pytest
      run: |
        pytest --cov=. --cov-report=xml