# .github/workflows/release.yml

name: Build, Sign, and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
    outputs:
      app_version: ${{ steps.set_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Create Version File
        id: set_version
        run: |
          VERSION=${{ github.ref_name }}
          echo "__version__ = '${VERSION#v}'" > version.py
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
        shell: bash
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install pyinstaller
      - name: Build the application
        run: >
          pyinstaller --noconfirm --onefile --windowed
          --name "btx-sync"
          --icon="${{ runner.os == 'Windows' && 'assets/icon.ico' || 'assets/icon.icns' }}"
          --add-data "assets${{ env.pathsep }}assets"
          --add-data "README.md${{ env.pathsep }}."
          --add-data "repository/metadata/root.json${{ env.pathsep }}repository/metadata"
          app.py
        env:
          pathsep: "${{ runner.os == 'Windows' && ';' || ':' }}"
      - name: Package macOS App
        if: runner.os == 'macOS'
        run: (cd dist && zip -r btx-sync-macOS.zip btx-sync.app)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: btx-sync-${{ runner.os }}
          path: |
            ${{ runner.os == 'macOS' && 'dist/btx-sync-macOS.zip' || '' }}
            ${{ runner.os == 'Windows' && 'dist/btx-sync.exe' || '' }}
            ${{ runner.os == 'Linux' && 'dist/btx-sync' || '' }}

  release:
    name: Sign, Release, and Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Process and Sign All Platforms
        env:
          TUF_ROOT_KEY: ${{ secrets.TUF_ROOT_PRIVATE_KEY }}
          TUF_SNAPSHOT_KEY: ${{ secrets.TUF_SNAPSHOT_PRIVATE_KEY }}
          TUF_TARGETS_KEY: ${{ secrets.TUF_TARGETS_PRIVATE_KEY }}
          TUF_TIMESTAMP_KEY: ${{ secrets.TUF_TIMESTAMP_PRIVATE_KEY }}
        run: |
          set -e
          pip install tufup==0.9.0
          
          mkdir -p keystore
          echo "$TUF_ROOT_KEY" > keystore/root
          echo "$TUF_SNAPSHOT_KEY" > keystore/snapshot
          echo "$TUF_TARGETS_KEY" > keystore/targets
          echo "$TUF_TIMESTAMP_KEY" > keystore/timestamp

          APP_VERSION="${{ needs.build.outputs.app_version }}"
          PLATFORMS="win:windows-latest mac:macos-latest linux:ubuntu-latest"

          for platform_info in $PLATFORMS; do
            IFS=':' read -r p_suffix p_os <<< "$platform_info"
            echo "--- Processing platform: $p_suffix ---"

            rm -rf temp_workspace
            mkdir -p temp_workspace
            cd temp_workspace

            # 1. Create the required repository and keystore subdirectories
            mkdir -p repository/metadata repository/targets
            cp -r ../keystore ./

            # 2. Copy the base JSON config and use `jq` to update the app_name
            #    This assumes your base config file is named `.tufup-repo-config` in the project root.
            jq --arg new_name "btx-sync-$p_suffix" '.app_name = $new_name' ../.tufup-repo-config > ./.tufup-repo-config

            # 3. Copy ALL existing metadata from the project's repository.
            cp -a ../repository/metadata/. ./repository/metadata/

            # 4. Add the new application bundle to the repository.
            tufup targets add "$APP_VERSION" "../artifacts/btx-sync-$p_os" keystore
            
            # 5. Sign all roles to commit the new target.
            for role in root targets snapshot timestamp; do
              tufup sign "$role" keystore
            done

            # 6. Copy the completed repository to the final deployment directory.
            mkdir -p ../deploy_repo/$p_suffix
            cp -a ./repository/. ../deploy_repo/$p_suffix/
            
            cd ..
          done
      
      - name: Verify Repository Contents
        run: ls -R deploy_repo

      - name: Deploy Update Files to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_repo
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create ${{ github.ref_name }}
          --title "Release ${{ github.ref_name }}"
          --notes "Download the application for your OS below."
          --prerelease=${{ contains(github.ref, 'a') || contains(github.ref, 'b') || contains(github.ref, 'rc') }}
          
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release upload ${{ github.ref_name }}
          ./artifacts/btx-sync-windows-latest/btx-sync.exe#btx-sync-Windows.exe
          ./artifacts/btx-sync-macos-latest/btx-sync-macOS.zip#btx-sync-macOS.zip
          ./artifacts/btx-sync-ubuntu-latest/btx-sync#btx-sync-Linux